{% set version = "1.1.4" %}
{% set posix = 'm2-' if win else '' %}

package:
  name: r-cyphr
  version: {{ version|replace("-", "_") }}

source:
  url:
    - {{ cran_mirror }}/src/contrib/cyphr_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/cyphr/cyphr_{{ version }}.tar.gz
  sha256: 3d2567030f065a0acb296ef9764dc621988dfca559342ed12fba3932579d9f9e

build:
  number: 3
  noarch: generic
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - {{ posix }}zip  # [win]
  host:
    - r-base
    - r-getpass
    - r-openssl >=0.9.9
    - r-sodium >=1.2.1
  run:
    - r-base
    - r-getpass
    - r-openssl >=0.9.9
    - r-sodium >=1.2.1

test:
  commands:
    - $R -e "library('cyphr')"           # [not win]
    - "\"%R%\" -e \"library('cyphr')\""  # [win]

about:
  home: https://github.com/ropensci/cyphr
  license: MIT
  license_file: LICENSE
  summary: Encryption wrappers, using low-level support from 'sodium' and 'openssl'.  'cyphr' tries to smooth over some pain points when using encryption within applications and data analysis by wrapping around differences in function names and arguments in different encryption providing packages.  It also provides high-level
    wrappers for input/output functions for seamlessly adding encryption to existing analyses.
  license_family: MIT

extra:
  recipe-maintainers:
    - conda-forge/r
    - ocefpaf
