travis:
  secure:
    BINSTAR_TOKEN: Qrz+Is7/FeO1KcpP49bsW5PxmurhU8dauTVEUYNdHZ8tW9SYW0DbWwJsiFR8/SAOuk0jJvfnkKMXbgHX/RepSm4udrH5k78p9f6+FxyPQMIqC6pfnfWjmVxAkdqViTPOtcdVHXjk6nqufYbHvN5ZjbcjuuIVuTq/uTB8hGTGZUqXhVjvlkdK2Dy1Hb4wbLjB6UrEIrYvhJeg0JTgR4N47ye5gbqivNA4qmaBdfcR7Nm2PSRl6hMyLxiqBHwCL+6H1/Ybkbx0Xs1ygfCuEFGnVg8mIWwBtV//+7AC/0EdY+VZZRa4xf+4FcErM1caPIBwhZXRkK/hrwPpfLYFF7TCoKd6p/9fVS7cnUN68IuiOid2QZNlGNKyFvzCOLke37K4KPrsfbBlucu/mhLgmrxuoXOHRlMr3R2fRSs42pqezFhCD8EocW9F/EfQV8w8KHxvGI9xC6qVmmtlDZ5ctmMg+g8jcyFnctU+XgA3VMibPtdFVDe9DxUT256PY+etDAs+TqvuYWIpV0yEmmHcf0MFbEiHDHtl7J5C1b9ea41Tlbml0kOPWDZqW4mWNic9GEu8jEVHps/gDbTLeAtJX5rJh1vpLpaeKyCoqVIZKOxPiu0WBlpc4XKk8kkUzCFcoreSF6v+YHzzzkOx+CQVh3YZe3h9S9v+Lh8OP6H/nIXM0AE=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
